"""
evolve.py — The evolution loop.

Generate → score → keep or discard → mutate → repeat.

Run this and walk away. Check /history in the morning.
"""

import csv
import json
import os
import sys
import time
from datetime import datetime, timezone
from pathlib import Path

from generate import generate_full, load_brief, save_generation
from score import score_generation, save_score, load_generation

# ---------------------------------------------------------------------------
# Config
# ---------------------------------------------------------------------------
GENERATIONS = int(os.getenv("AUTOBRAND_GENERATIONS", "300"))
KEEP_TOP_N = 3
SCORE_THRESHOLD = 20
HISTORY_DIR = Path("history")

# ---------------------------------------------------------------------------
# State
# ---------------------------------------------------------------------------

def load_state() -> dict:
    state_path = HISTORY_DIR / "state.json"
    if state_path.exists():
        return json.loads(state_path.read_text())
    return {"current_gen": 0, "best_score": 0, "best_gen": None, "survivors": []}


def save_state(state: dict) -> None:
    HISTORY_DIR.mkdir(parents=True, exist_ok=True)
    (HISTORY_DIR / "state.json").write_text(json.dumps(state, indent=2))


def append_csv(gen_num: int, score: int, parent: int | None, critique: str) -> None:
    csv_path = HISTORY_DIR / "evolution.csv"
    write_header = not csv_path.exists()
    with open(csv_path, "a", newline="") as f:
        writer = csv.writer(f)
        if write_header:
            writer.writerow(["gen", "score", "parent", "timestamp", "critique_preview"])
        writer.writerow([
            gen_num, score, parent or "",
            datetime.now(timezone.utc).isoformat(),
            critique[:120] if critique else "",
        ])


def update_best(state: dict, gen_num: int, score: int) -> None:
    if score > state["best_score"]:
        state["best_score"] = score
        state["best_gen"] = gen_num
        (HISTORY_DIR / "best.json").write_text(json.dumps({
            "gen": gen_num, "score": score, "path": f"gen_{gen_num:03d}",
            "timestamp": datetime.now(timezone.utc).isoformat(),
        }, indent=2))


def pick_parent(state: dict) -> tuple[str | None, str | None, int | None, dict | None]:
    """Pick the best survivor. Returns (critique, suggestion, score, artifacts)."""
    if not state["survivors"]:
        return None, None, None, None

    best = max(state["survivors"], key=lambda s: s["score"])
    gen_dir = HISTORY_DIR / f"gen_{best['gen']:03d}"

    critique = suggestion = None
    score_path = gen_dir / "score.json"
    if score_path.exists():
        sd = json.loads(score_path.read_text())
        critique = sd.get("critique", "")
        suggestion = sd.get("suggestion", "")

    artifacts = load_generation(gen_dir)
    return critique, suggestion, best["score"], artifacts


def generate_summary(state: dict) -> None:
    csv_path = HISTORY_DIR / "evolution.csv"
    if not csv_path.exists():
        return

    rows = list(csv.DictReader(open(csv_path)))
    if not rows:
        return

    scores = [int(r["score"]) for r in rows]
    early = scores[:10]
    late = scores[-10:]

    summary = f"""# Evolution Summary

**Total generations:** {len(rows)}
**Best score:** {max(scores)}/100 (gen {state.get('best_gen', '?')})
**Worst score:** {min(scores)}/100
**Average:** {sum(scores)/len(scores):.1f}/100

## Trajectory

- First 10 avg: {sum(early)/len(early):.1f}
- Last 10 avg: {sum(late)/len(late):.1f}
- Improvement: {sum(late)/len(late) - sum(early)/len(early):+.1f} points

## Best generation

See `gen_{state.get('best_gen', 0):03d}/` for the highest-scoring identity system.

---

*Generated by autobrand at {datetime.now(timezone.utc).isoformat()}*
"""
    (HISTORY_DIR / "summary.md").write_text(summary)


# ---------------------------------------------------------------------------
# Main loop
# ---------------------------------------------------------------------------

def run():
    HISTORY_DIR.mkdir(parents=True, exist_ok=True)
    state = load_state()
    brief = load_brief()
    start_gen = state["current_gen"] + 1

    print("=" * 60)
    print("autobrand — autonomous brand evolution")
    print("=" * 60)
    print(f"brief: {len(brief)} chars")
    print(f"starting from generation {start_gen}")
    print(f"target: {GENERATIONS} generations")
    if state["best_gen"]:
        print(f"current best: {state['best_score']}/100 (gen {state['best_gen']})")
    print("=" * 60 + "\n")

    for gen_num in range(start_gen, GENERATIONS + 1):
        cycle_start = time.time()
        print(f"--- generation {gen_num}/{GENERATIONS} ---")

        critique, suggestion, parent_score, parent_artifacts = pick_parent(state)
        parent_gen = None

        if parent_artifacts:
            parent_gen = max(state["survivors"], key=lambda s: s["score"])["gen"]
            print(f"  parent: gen {parent_gen} (score {parent_score})")
        else:
            print("  fresh generation")

        # generate
        try:
            artifacts = generate_full(
                brief,
                critique=critique,
                suggestion=suggestion,
                score=parent_score,
                parent_artifacts=parent_artifacts,
            )
        except Exception as e:
            print(f"  ERROR: {e}")
            continue

        gen_dir = save_generation(gen_num, artifacts, HISTORY_DIR)

        meta = {
            "gen": gen_num, "parent": parent_gen,
            "timestamp": datetime.now(timezone.utc).isoformat(),
        }
        (gen_dir / "meta.json").write_text(json.dumps(meta, indent=2))

        # score
        print("  scoring...")
        try:
            score_data = score_generation(brief, artifacts)
            save_score(gen_dir, score_data)
        except Exception as e:
            print(f"  ERROR scoring: {e}")
            score_data = {"score": 0, "critique": str(e), "suggestion": ""}
            save_score(gen_dir, score_data)

        score = score_data.get("score", 0)
        critique_text = score_data.get("critique", "")

        append_csv(gen_num, score, parent_gen, critique_text)

        if score >= SCORE_THRESHOLD:
            state["survivors"].append({"gen": gen_num, "score": score})
            state["survivors"] = sorted(
                state["survivors"], key=lambda s: s["score"], reverse=True
            )[:KEEP_TOP_N]

        update_best(state, gen_num, score)
        state["current_gen"] = gen_num
        save_state(state)

        elapsed = time.time() - cycle_start
        print(f"  score: {score}/100")
        if score_data.get("suggestion"):
            print(f"  next: {score_data['suggestion'][:100]}")
        print(f"  best: {state['best_score']}/100 (gen {state['best_gen']})")
        print(f"  cycle: {elapsed:.1f}s\n")

    generate_summary(state)
    print("=" * 60)
    print("evolution complete.")
    print(f"best: gen {state['best_gen']} — score {state['best_score']}/100")
    print(f"see history/summary.md for the full report")
    print("=" * 60)


if __name__ == "__main__":
    run()
